name: gen_models
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"
dependencies:
  meta: ^1.12.0
  json_annotation: ^4.9.0
  source_gen: ^1.5.0
  analyzer: ^5.0.0
  synchronized: ^3.4.0
dev_dependencies:
  build_runner: ^2.4.0
  build: ^2.4.0
  source_gen: ^1.5.0
  test: ^1.24.0

flutter:
